# Generated by Django 4.2.4 on 2023-10-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='F1ower', max_length=20),
            preserve_default=False,
        ),
    ]
